# Generated by Django 5.0.2 on 2024-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
